Add custom pointT
sbgisen/removert pull request #1
Opened 2023-02-13 08:21 UTC by Alpaca-zip

## Summary
colorize_pcl、LIO-SAMと併用することで色情報を付与した点群の動的障害物を削除します。
- Before
<img src="https://user-images.githubusercontent.com/84959376/218400883-723ce760-8687-49ad-a0e7-19ac3724457c.png" width="500px">

- After
<img src="https://user-images.githubusercontent.com/84959376/218401211-dbabb17b-e6d8-401b-ba8f-ea4a3cae0fbe.png" width="500px">

## Detail
このPRではpclのカスタム型PointTの導入とテンプレートの導入によって色情報を含む点群でも動的障害物を削除できるように実装しています。実行の際にはcolorize_pclが[feature/add_custom_pointT](https://github.com/sbgisen/colorize_pcl/tree/feature/add_custom_pointT)ブランチ、LIO-SAMが[feature/removert](https://github.com/sbgisen/LIO-SAM/tree/feature/removert)ブランチ、wheeltec_robotが[feature/removert](https://github.com/sbgisen/wheeltec_robot/tree/feature/removert)ブランチであることをご確認ください。

## 実行方法
###  1. removert用のPCDとoptimized_poses.txtを用意する
removertを利用するためには以下のように、キーフレームごとのPCDファイルとoptimized_poses.txtという姿勢データが必要になります。

<img src="https://user-images.githubusercontent.com/84959376/218403912-316663b3-c754-4895-a9ec-15bca813c4fe.png" width="300px"><img src="https://user-images.githubusercontent.com/84959376/218403976-c3b1fb9d-4a20-4cd4-8807-87e29aac52b4.png" width="300px">

これらをLIO-SAMで出力させるための方法は以下の通りです。いずれも`Ctrl+c`でLIO-SAMが終了するときに`~/Downloads/LOAM/`にファイルが保存されます。
- gazeboシミュレーション
```
roslaunch wheeltec_create_map lio_sam_slam.launch
roslaunch wheeltec_gazebo wheeltec_gazebo.launch world_name:='$(find private_gazebo_worlds)/worlds/tsukuba_start_area.world'
roslaunch wheeltec_teleop joy_control.launch
```
- rosbag
```
roslaunch wheeltec_bringup with_rosbag.launch
roslaunch wheeltec_create_map lio_sam_slam.launch
rosbag play your_bag.bag --clock
```
###  2. removertの実行
実行前に[removert.launch](https://github.com/sbgisen/wheeltec_robot/blob/feature/removert/wheeltec_create_map/launch/removert.launch)の`save_pcd_directory`、`sequence_scan_dir`、`sequence_pose_path`を適宜変更してください。
- `save_pcd_directory`：removertの出力結果を保存する場所。
- `sequence_scan_dir`：キーフレームごとのPCDファイルの場所。
- `sequence_pose_path`：optimized_poses.txtの場所。

実行コマンド
```
roslaunch wheeltec_create_map removert.launch
```

## Test
* [x] つくばチャレンジでのrosbagで動作確認

  

## Attention

removertのbuildには、gccのバージョンが8以上である必要があります。

2023-02-16 02:45 UTC, Tacha-S requested changes
なんかRemoverterのクラスがuse_rgbで分岐したいのかtemplateに与えられた型で動きを変えたいのかわからない中途半端な感じがします

2023-02-16 02:45 UTC, Tacha-S commented on config/params_mulran_scliosam.yaml
> +  sequence_pose_path: "/home/gisen/Downloads/LOAM/optimized_poses.txt"
ここらへんlaunch時に上書きするようにしていると思うんですが、
https://github.com/sbgisen/wheeltec_robot/blob/2f161c61a507d4765c59ededd89985d941ea0eb2/wheeltec_create_map/launch/removert.launch#L6-L8

変える必要ありますか？

2023-02-16 03:10 UTC, Tacha-S commented
中途半端というと困らせるだけだと思うので追記しておくと、
内容完全に精査はできてませんが、色付きか否かによって分けている関数が`convertPointCloud`するかしないか(色の情報を型として落とすかどうか)しかしてないならuse_rgbのbool持っているのでそこだけ分岐すれば良さそうなものを、
use_rgbの分岐でtemplateの型を変えて実行される関数を変えていて冗長だと思います。

2023-02-16 03:13 UTC, Alpaca-zip commented on config/params_mulran_scliosam.yaml
> +  sequence_pose_path: "/home/gisen/Downloads/LOAM/optimized_poses.txt"
現状、lio_samはKeyFramePCDsとoptimized_poses.txtを`~/Downloads/LOAM`に保存するようになっているので、それに合わせてpathを変更しましたが、変更する前のデフォルトの方がよろしいですか？

2023-02-16 03:17 UTC, Alpaca-zip commented
@Tacha-S 
レビューいただきありがとうございます。
確かにおっしゃるとおりです。冗長な箇所のリファクタリングを行って改善してみようと思います。

2023-02-16 03:21 UTC, Alpaca-zip commented
一度こちらのPRはドラフトに戻させていただきます。

2023-02-16 03:25 UTC, Tacha-S commented on config/params_mulran_scliosam.yaml
> +  sequence_pose_path: "/home/gisen/Downloads/LOAM/optimized_poses.txt"
run_scliosam.launchを使う想定であればsubst_value="true"にして`$(env HOME)/Downloads...`にしてほしいですし、
使わない(wheeltec_create_mapのlaunchを使ってもらう)想定であれば明らかにpathが異なるのでここを変えても他の箇所で上書きされていて意味がないことを暗黙的に示せると思います。

2023-02-16 03:39 UTC, Alpaca-zip commented on config/params_mulran_scliosam.yaml
> +  sequence_pose_path: "/home/gisen/Downloads/LOAM/optimized_poses.txt"
例えばwheeltec_create_mapの[removert.launch](https://github.com/sbgisen/wheeltec_robot/blob/2f161c61a507d4765c59ededd89985d941ea0eb2/wheeltec_create_map/launch/removert.launch)を利用する場合には、launchファイル内のargで上書きしているので、removertの[params_mulran_scliosam.yaml](https://github.com/sbgisen/removert/blob/99c9ba1edca5560f00628cb0291d079936ca6c06/config/params_mulran_scliosam.yaml)のパラメータを変更する必要はないというような認識で合ってますでしょうか。

2023-02-16 04:35 UTC, Tacha-S commented on config/params_mulran_scliosam.yaml
> +  sequence_pose_path: "/home/gisen/Downloads/LOAM/optimized_poses.txt"
そうです。

2023-02-16 04:54 UTC, Alpaca-zip commented on config/params_mulran_scliosam.yaml
> +  sequence_pose_path: "/home/gisen/Downloads/LOAM/optimized_poses.txt"
こちらの件、理解できました。
[params_mulran_scliosam.yaml](https://github.com/sbgisen/removert/blob/99c9ba1edca5560f00628cb0291d079936ca6c06/config/params_mulran_scliosam.yaml)はデフォルトに戻させていただきます。ご指摘いただきありがとうございました。

2023-02-24 05:04 UTC, Alpaca-zip commented
@Tacha-S 
テンプレートを利用せず、`use_rgb`の分岐によってrgbフィールドを持った地図を保存するか否かを決めるように実装しなおしました。これで冗長な部分は解消されたように思いますがいかがでしょうか。今一度レビューいただけますと幸いです。

**補足**
点群のダウンサンプルにOctreePointCloudVoxelCentroidを利用すると、下の図のように点群に適切でない色が載ってしまう現象があったため、`use_rgb`が`true`のときはVoxelGridを利用するように変更しています。

<img src="https://user-images.githubusercontent.com/84959376/221095658-febc8859-50e7-4899-8e4a-354d9e6c92b7.png" width="500px">

https://github.com/sbgisen/removert/blob/c8e8e1b38a68646a41265b4ea79bc185228338cf/src/Removerter.cpp#L296-L321

2023-02-27 08:17 UTC, Tacha-S requested changes
`savePCDwithoutRGBBinary()`という関数を作るなら、
`savePCD()`のようにして
呼び出し時はifで分けずに、`savePCD()`を呼び出し
`savePCD()`のなかで
```cpp
if(use_rgb)
    {
        pcl::io::savePCDFileBinary(static_file_name, *map_local_curr_static);
    }
    else
    {
        // savePCDwithoutRGBBinaryの中身
    }
```
のようにしたほうがいいと思います。

2023-02-28 08:14 UTC, Alpaca-zip commented
> `savePCDwithoutRGBBinary()`という関数を作るなら、 `savePCD()`のようにして 呼び出し時はifで分けずに、`savePCD()`を呼び出し `savePCD()`のなかで
> 
> ```c++
> if(use_rgb)
>     {
>         pcl::io::savePCDFileBinary(static_file_name, *map_local_curr_static);
>     }
>     else
>     {
>         // savePCDwithoutRGBBinaryの中身
>     }
> ```
> 
> のようにしたほうがいいと思います。

レビューいただきありがとうございます。こちらの件、再度改善してみましたがいかがでしょうか。

2023-03-07 00:09 UTC, Tacha-S approved these changes

2023-03-07 00:10 UTC, merged